---

- name: config > Enable shorewall daemon.
  lineinfile :
    dest:  /etc/default/shorewall
    regexp: "^startup="
    line: "startup=1"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - shorewall restart

# BEWARE! By default, Shorewall allows all IPV6 traffic (open bar).
# If our system enables IPV6 (most do nowdays), we have to disable it or set up Shorewall6.
- name: config > Set IPV6 default policy
  lineinfile :
    dest:  /etc/shorewall/shorewall.conf
    regexp: "^DISABLE_IPV6="
    line: "DISABLE_IPV6={{ elao_shorewall_disable_ipv6 }}"
  notify:
    - shorewall restart
    
- name: config > Writing params file.
  copy:
    src:   "{{ item }}"
    dest:  /etc/shorewall/{{ item }}
    owner: root
    group: root
    mode:  0644
  with_items:
    - params

- name: config > Writing files.
  template:
    src:  "{{ item.src }}"
    dest: /etc/shorewall/{{ item.dest }}
  with_items:
    - { src: "{{ elao_shorewall_config_templates.policy }}",     dest: policy }
    - { src: "{{ elao_shorewall_config_templates.masq }}",       dest: masq }
    - { src: "{{ elao_shorewall_config_templates.interfaces }}", dest: interfaces }
    - { src: "{{ elao_shorewall_config_templates.zones }}",      dest: zones }
    - { src: "{{ elao_shorewall_config_templates.rules }}",      dest: rules }
  notify:
    - shorewall restart
